# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole site, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/


### Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Simulating eXtreme Spacetimes
email: questions@black-holes.org
description: >-
    The SXS project is a collaborative research effort involving multiple
    institutions. Our goal is the simulation of black holes and other extreme
    spacetimes to gain a better understanding of Relativity, and the physics of
    exotic objects in the distant cosmos.
baseurl: "/www_black-holes_org" # the subpath of your site, e.g. /blog
domain: "moble.github.io"
url: "https://www.black-holes.org" # the base hostname & protocol for your site, e.g. https://example.com
twitter_username: SXSProject
github_username:  sxs-collaboration


collections:
  - people
  - glossary
  - institutions
  - papers

### Build settings

# See the basic theme at <https://github.com/jekyll/minima>; it gets overridden by our own layouts
# to some extent.
theme: minima

plugins:
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-titles-from-headings
  - jekyll-sitemap
  - jekyll-redirect-from

sass:
  style: compressed

# Don't add the output extension (.html) to the url of posts
permalink: /:categories/:year/:month/:day/:title

### Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
exclude:
  - Gemfile
  - Gemfile.lock
  - _original_pages
  - _original_logos


# This is configuration for the `compress` _layout; see https://jch.penibelst.de/
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  blanklines: false


# Note that we have to set `collections` to `true` to process posts correctly; usually their titles
# are created based on the filename alone, which is ugly.
titles_from_headings:
  enabled:     true
  strip_title: true
  collections: true
